// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/oos/order/changeOrder": {
            "put": {
                "description": "ChangeOrder 주문 변경 - 주문자 (주문변경 커멘드 Enums(주문추가, 주문취소, 정보변경))",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call ChangeOrder, return ok by json.",
                "parameters": [
                    {
                        "description": "오더",
                        "name": "OrdererMenuLink",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OrdererMenuLink"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Controller"
                        }
                    }
                }
            }
        },
        "/oos/order/createReview": {
            "post": {
                "description": "CreateReview 리뷰 등록 - 주문자 (주문번호 기준으로 등록)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call CreateReview, return ok by json.",
                "parameters": [
                    {
                        "description": "오더",
                        "name": "OrdererMenuLink",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OrdererMenuLink"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.OrdererMenuLink"
                        }
                    }
                }
            }
        },
        "/oos/order/newOrder": {
            "post": {
                "description": "NewOrder 주문 등록 - 주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call NewOrder, return ok by json.",
                "parameters": [
                    {
                        "description": "오더",
                        "name": "OrdererMenuLink",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OrdererMenuLink"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.OrdererMenuLink"
                        }
                    }
                }
            }
        },
        "/oos/order/searchOrder": {
            "get": {
                "description": "SearchOrder 주문 내역 조회 기능 - 주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call SearchOrder, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "주문자 ID",
                        "name": "OrdererID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "주문확인중",
                            "조리중",
                            "배달중",
                            "배달완료",
                            "주문취소"
                        ],
                        "type": "string",
                        "description": "주문 상태",
                        "name": "OrderStatus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Controller"
                        }
                    }
                }
            }
        },
        "/oos/order/searchTodayMenu": {
            "get": {
                "description": "SearchTodayMenu 오늘의 추천메뉴 리스트",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call SearchTodayMenu, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "판매자 ID",
                        "name": "SellerID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "가격",
                        "name": "Price",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "한국",
                            "일본",
                            "중국"
                        ],
                        "type": "string",
                        "description": "원산지",
                        "name": "CountryOf",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "한식",
                            "일식",
                            "중식"
                        ],
                        "type": "string",
                        "description": "메뉴 카테고리",
                        "name": "Category",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "준비중",
                            "판매중"
                        ],
                        "type": "string",
                        "description": "주문 가능 상태",
                        "name": "Status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "아주매움",
                            "매움",
                            "보통",
                            "순한맛"
                        ],
                        "type": "string",
                        "description": "맵기",
                        "name": "Spicy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Controller"
                        }
                    }
                }
            }
        },
        "/oos/order/viewMenu": {
            "get": {
                "description": "ViewMenu 메뉴 상세 - 주문자, 피주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call ViewMenu, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴 ID",
                        "name": "MenuID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                }
            }
        },
        "/oos/order/viewOrder": {
            "get": {
                "description": "ViewOrder 주문 상세 - 주문자, 피주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call ViewOrder, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "주문번호",
                        "name": "OrderNo",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Controller"
                        }
                    }
                }
            }
        },
        "/oos/seller/createMenu": {
            "post": {
                "description": "CreateMenu 메뉴 등록 - 피주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call CreateMenu, return ok by json.",
                "parameters": [
                    {
                        "description": "메뉴",
                        "name": "Menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                }
            }
        },
        "/oos/seller/deleteMenu": {
            "put": {
                "description": "DeleteMenu 메뉴 삭제 - 피주문자 (판매여부 bool 설정변경)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call DeleteMenu, return ok by json.",
                "parameters": [
                    {
                        "description": "메뉴",
                        "name": "Menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                }
            }
        },
        "/oos/seller/orderStatus": {
            "get": {
                "description": "OrderStatus 주문 내역 조회 - 피주문자 (판매자ID 기준으로 검색)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call OrderStatus, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "판매자 ID",
                        "name": "SellerID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "주문확인중",
                            "조리중",
                            "배달중",
                            "배달완료",
                            "주문취소"
                        ],
                        "type": "string",
                        "description": "주문 상태",
                        "name": "OrderStatus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Controller"
                        }
                    }
                }
            }
        },
        "/oos/seller/searchMenu": {
            "get": {
                "description": "SearchMenu 메뉴 검색 - 주문자, 피주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call SearchMenu, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "판매자 ID",
                        "name": "SellerID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "가격",
                        "name": "Price",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "한국",
                            "일본",
                            "중국"
                        ],
                        "type": "string",
                        "description": "원산지",
                        "name": "CountryOf",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "한식",
                            "일식",
                            "중식"
                        ],
                        "type": "string",
                        "description": "메뉴 카테고리",
                        "name": "Category",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "준비중",
                            "판매중",
                            "판매완료"
                        ],
                        "type": "string",
                        "description": "주문 가능 상태",
                        "name": "Status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "아주매움",
                            "매움",
                            "보통",
                            "순한맛"
                        ],
                        "type": "string",
                        "description": "맵기",
                        "name": "Spicy",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "오늘의 추천메뉴 여부",
                        "name": "TodayMenu",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Controller"
                        }
                    }
                }
            }
        },
        "/oos/seller/setTodayMenu": {
            "put": {
                "description": "SetTodayMenu 오늘의 추천메뉴 여부 - 설정 변경 (메뉴ID를 기준으로 메뉴 업데이트)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call SetTodayMenu, return ok by json.",
                "parameters": [
                    {
                        "description": "메뉴",
                        "name": "Menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                }
            }
        },
        "/oos/seller/updateMenu": {
            "post": {
                "description": "UpdateMenu 메뉴 수정 - 피주문자 (메뉴ID를 기준으로 메뉴 업데이트)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call UpdateMenu, return ok by json.",
                "parameters": [
                    {
                        "description": "메뉴",
                        "name": "Menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Menu"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Controller": {
            "type": "object"
        },
        "model.Menu": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "메뉴 카테고리 Enums(한식, 일식, 중식)",
                    "type": "string"
                },
                "countryOf": {
                    "description": "원산지 Enums(한국, 일본, 중국)",
                    "type": "string"
                },
                "isDisabled": {
                    "description": "판매여부 default(true)",
                    "type": "boolean"
                },
                "maxCount": {
                    "description": "판매 가능 갯수 mininum(1) maxinum(50)",
                    "type": "integer"
                },
                "menuID": {
                    "description": "메뉴 ID",
                    "type": "string"
                },
                "menuName": {
                    "description": "메뉴 이름",
                    "type": "string"
                },
                "popularity": {
                    "description": "인기도 mininum(1) maxinum(5)",
                    "type": "integer"
                },
                "price": {
                    "description": "가격",
                    "type": "integer"
                },
                "sellerID": {
                    "description": "판매자 ID",
                    "type": "string"
                },
                "sellerName": {
                    "description": "판매자 이름",
                    "type": "string"
                },
                "spicy": {
                    "description": "맵기 Enums(아주매움, 매움, 보통, 순한맛)",
                    "type": "string"
                },
                "status": {
                    "description": "주문 가능 상태 nums(준비중, 판매중)",
                    "type": "string"
                },
                "todayMenu": {
                    "description": "오늘의 추천메뉴 여부 default(false)",
                    "type": "boolean"
                }
            }
        },
        "model.OrdererMenuLink": {
            "type": "object",
            "properties": {
                "menuID": {
                    "description": "메뉴 ID",
                    "type": "string"
                },
                "menuName": {
                    "description": "메뉴이름",
                    "type": "string"
                },
                "orderComment": {
                    "description": "후기",
                    "type": "string"
                },
                "orderNo": {
                    "description": "주문번호",
                    "type": "string"
                },
                "orderStarGrade": {
                    "description": "평점 mininum(1) maxinum(5)",
                    "type": "integer"
                },
                "orderStatus": {
                    "description": "주문상태 Enums(주문확인중 - 조리중 - 배달중 - 배달완료 - 주문취소)",
                    "type": "string"
                },
                "ordererAddress": {
                    "description": "주문자 주소",
                    "type": "string"
                },
                "ordererID": {
                    "description": "주문자ID",
                    "type": "string"
                },
                "ordererPhone": {
                    "description": "주문자 폰번호",
                    "type": "integer"
                },
                "sellerID": {
                    "description": "판매자 ID",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "WBA [Backend Final Project]",
	Description:      "띵동주문이요, 온라인 주문 시스템(Online Ordering System)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
