// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/oos/order/changeOrder": {
            "post": {
                "description": "ChangeOrder 주문 변경 - 주문자 (수정/취소)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call ChangeOrder, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "주문자 ID",
                        "name": "OrdererID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "준비중",
                            "주문취소",
                            "배달중",
                            "배달완료"
                        ],
                        "type": "string",
                        "description": "주문 상태",
                        "name": "OrderStatus",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "주문자 주소",
                        "name": "OrdererAddress",
                        "in": "path"
                    },
                    {
                        "type": "integer",
                        "description": "주문자 폰번호",
                        "name": "OrdererPhone",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.OrdererMenuLink"
                        }
                    }
                }
            }
        },
        "/oos/order/createReview": {
            "post": {
                "description": "CreateReview 리뷰 등록 - 주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call CreateReview, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "주문자 ID",
                        "name": "OrdererID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "후기",
                        "name": "OrderComment",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "평점",
                        "name": "OrderStarGrade",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.OrdererMenuLink"
                        }
                    }
                }
            }
        },
        "/oos/order/newOrder": {
            "post": {
                "description": "NewOrder 주문 등록 - 주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call NewOrder, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "주문자 ID",
                        "name": "OrdererID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "준비중",
                            "주문취소",
                            "배달중",
                            "배달완료"
                        ],
                        "type": "string",
                        "description": "주문 상태",
                        "name": "OrderStatus",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "주문자 주소",
                        "name": "OrdererAddress",
                        "in": "path"
                    },
                    {
                        "type": "integer",
                        "description": "주문자 폰번호",
                        "name": "OrdererPhone",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.OrdererMenuLink"
                        }
                    }
                }
            }
        },
        "/oos/order/searchMenu": {
            "post": {
                "description": "SearchMenu 메뉴 검색 - 주문자, 피주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call SearchMenu, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "가격",
                        "name": "Price",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "한국",
                            "일본",
                            "중국"
                        ],
                        "type": "string",
                        "description": "원산지",
                        "name": "CountryOf",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "한식",
                            "일식",
                            "중식"
                        ],
                        "type": "string",
                        "description": "메뉴 카테고리",
                        "name": "Category",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "준비중",
                            "판매중"
                        ],
                        "type": "string",
                        "description": "주문 가능 상태",
                        "name": "Status",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "아주매움",
                            "매움",
                            "보통",
                            "순한맛"
                        ],
                        "type": "string",
                        "description": "맵기",
                        "name": "Spicy",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "오늘의 추천메뉴 여부",
                        "name": "TodayMenu",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.Menu"
                            }
                        }
                    }
                }
            }
        },
        "/oos/order/searchOrder": {
            "post": {
                "description": "SearchOrder 주문 내역 조회 기능 - 주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call SearchOrder, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "준비중",
                            "주문취소",
                            "배달중",
                            "배달완료"
                        ],
                        "type": "string",
                        "description": "주문 상태",
                        "name": "OrderStatus",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.OrdererMenuLink"
                            }
                        }
                    }
                }
            }
        },
        "/oos/order/viewMenu": {
            "post": {
                "description": "ViewMenu 메뉴 상세 - 주문자, 피주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call ViewMenu, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Menu"
                        }
                    }
                }
            }
        },
        "/oos/seller/OrderStatus": {
            "post": {
                "description": "OrderStatus 주문 내역 조회 - 피주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call OrderStatus, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "준비중",
                            "주문취소",
                            "배달중",
                            "배달완료"
                        ],
                        "type": "string",
                        "description": "주문 상태",
                        "name": "OrderStatus",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.OrdererMenuLink"
                            }
                        }
                    }
                }
            }
        },
        "/oos/seller/createMenu": {
            "post": {
                "description": "CreateMenu 메뉴 등록 - 피주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call CreateMenu, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "가격",
                        "name": "Price",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "한국",
                            "일본",
                            "중국"
                        ],
                        "type": "string",
                        "description": "원산지",
                        "name": "CountryOf",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "한식",
                            "일식",
                            "중식"
                        ],
                        "type": "string",
                        "description": "메뉴 카테고리",
                        "name": "Category",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "준비중",
                            "판매중"
                        ],
                        "type": "string",
                        "description": "주문 가능 상태",
                        "name": "Status",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "판매 가능 갯수",
                        "name": "MaxCount",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "아주매움",
                            "매움",
                            "보통",
                            "순한맛"
                        ],
                        "type": "string",
                        "description": "맵기",
                        "name": "Spicy",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "판매여부",
                        "name": "IsDisabled",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "오늘의 추천메뉴 여부",
                        "name": "TodayMenu",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Menu"
                        }
                    }
                }
            }
        },
        "/oos/seller/deleteMenu": {
            "put": {
                "description": "DeleteMenu 메뉴 삭제 - 피주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call DeleteMenu, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "판매여부",
                        "name": "IsDisabled",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Menu"
                        }
                    }
                }
            }
        },
        "/oos/seller/updateMenu": {
            "post": {
                "description": "UpdateMenu 메뉴 수정 - 피주문자",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "call UpdateMenu, return ok by json.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "메뉴이름",
                        "name": "MenuName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "가격",
                        "name": "Price",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "한국",
                            "일본",
                            "중국"
                        ],
                        "type": "string",
                        "description": "원산지",
                        "name": "CountryOf",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "한식",
                            "일식",
                            "중식"
                        ],
                        "type": "string",
                        "description": "메뉴 카테고리",
                        "name": "Category",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "준비중",
                            "판매중"
                        ],
                        "type": "string",
                        "description": "주문 가능 상태",
                        "name": "Status",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "판매 가능 갯수",
                        "name": "MaxCount",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "아주매움",
                            "매움",
                            "보통",
                            "순한맛"
                        ],
                        "type": "string",
                        "description": "맵기",
                        "name": "Spicy",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "판매여부",
                        "name": "IsDisabled",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "오늘의 추천메뉴 여부",
                        "name": "TodayMenu",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Menu"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Menu": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "메뉴 카테고리",
                    "type": "string"
                },
                "countryOf": {
                    "description": "원산지",
                    "type": "string"
                },
                "isDisabled": {
                    "description": "판매여부",
                    "type": "boolean"
                },
                "maxCount": {
                    "description": "판매 가능 갯수",
                    "type": "integer"
                },
                "menuName": {
                    "description": "메뉴 이름",
                    "type": "string"
                },
                "popularity": {
                    "description": "인기도",
                    "type": "integer"
                },
                "price": {
                    "description": "가격",
                    "type": "integer"
                },
                "sellerName": {
                    "description": "MenuID     string             ` + "`" + `bson:\"menuID\"` + "`" + `     //메뉴 ID",
                    "type": "string"
                },
                "spicy": {
                    "description": "맵기",
                    "type": "string"
                },
                "status": {
                    "description": "주문 가능 상태",
                    "type": "string"
                },
                "todayMenu": {
                    "description": "오늘의 추천메뉴 여부",
                    "type": "boolean"
                }
            }
        },
        "controller.OrdererMenuLink": {
            "type": "object",
            "properties": {
                "menuName": {
                    "description": "메뉴이름",
                    "type": "string"
                },
                "orderComment": {
                    "description": "후기",
                    "type": "string"
                },
                "orderNo": {
                    "description": "주문번호",
                    "type": "string"
                },
                "orderStarGrade": {
                    "description": "평점",
                    "type": "integer"
                },
                "orderStatus": {
                    "description": "주문상태",
                    "type": "string"
                },
                "ordererAddress": {
                    "description": "주문자 주소",
                    "type": "string"
                },
                "ordererID": {
                    "description": "주문자ID",
                    "type": "integer"
                },
                "ordererPhone": {
                    "description": "주문자 폰번호",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "WBA [Backend Final Project]",
	Description:      "띵동주문이요, 온라인 주문 시스템(Online Ordering System)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
