definitions:
  controller.Controller:
    type: object
  model.Menu:
    properties:
      category:
        description: 메뉴 카테고리 Enums(한식, 일식, 중식)
        type: string
      countryOf:
        description: 원산지 Enums(한국, 일본, 중국)
        type: string
      isDisabled:
        description: 판매여부 default(true)
        type: boolean
      maxCount:
        description: 판매 가능 갯수 mininum(1) maxinum(50)
        type: integer
      menuID:
        description: 메뉴 ID
        type: string
      menuName:
        description: 메뉴 이름
        type: string
      popularity:
        description: 인기도 mininum(1) maxinum(5)
        type: integer
      price:
        description: 가격
        type: integer
      sellerID:
        description: 판매자 ID
        type: string
      sellerName:
        description: 판매자 이름
        type: string
      spicy:
        description: 맵기 Enums(아주매움, 매움, 보통, 순한맛)
        type: string
      status:
        description: 주문 가능 상태 nums(준비중, 판매중)
        type: string
      todayMenu:
        description: 오늘의 추천메뉴 여부 default(false)
        type: boolean
    type: object
  model.OrdererMenuLink:
    properties:
      menuID:
        description: 메뉴 ID
        type: string
      menuName:
        description: 메뉴이름
        type: string
      orderComment:
        description: 후기
        type: string
      orderNo:
        description: 주문번호
        type: string
      orderStarGrade:
        description: 평점 mininum(1) maxinum(5)
        type: integer
      orderStatus:
        description: 주문상태 Enums(주문확인중 - 조리중 - 배달중 - 배달완료 - 주문취소)
        type: string
      ordererAddress:
        description: 주문자 주소
        type: string
      ordererID:
        description: 주문자ID
        type: string
      ordererPhone:
        description: 주문자 폰번호
        type: integer
      sellerID:
        description: 판매자 ID
        type: string
    type: object
info:
  contact: {}
  description: 띵동주문이요, 온라인 주문 시스템(Online Ordering System)
  title: WBA [Backend Final Project]
  version: "1.0"
paths:
  /oos/order/changeOrder:
    put:
      consumes:
      - application/json
      description: ChangeOrder 주문 변경 - 주문자 (주문변경 커멘드 Enums(주문추가, 주문취소, 정보변경))
      parameters:
      - description: 오더
        in: body
        name: OrdererMenuLink
        required: true
        schema:
          $ref: '#/definitions/model.OrdererMenuLink'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call ChangeOrder, return ok by json.
  /oos/order/createReview:
    post:
      consumes:
      - application/json
      description: CreateReview 리뷰 등록 - 주문자 (주문번호 기준으로 등록)
      parameters:
      - description: 오더
        in: body
        name: OrdererMenuLink
        required: true
        schema:
          $ref: '#/definitions/model.OrdererMenuLink'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OrdererMenuLink'
      summary: call CreateReview, return ok by json.
  /oos/order/newOrder:
    post:
      consumes:
      - application/json
      description: NewOrder 주문 등록 - 주문자
      parameters:
      - description: 오더
        in: body
        name: OrdererMenuLink
        required: true
        schema:
          $ref: '#/definitions/model.OrdererMenuLink'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OrdererMenuLink'
      summary: call NewOrder, return ok by json.
  /oos/order/searchMenu:
    get:
      consumes:
      - application/json
      description: SearchMenu 메뉴 검색 - 주문자, 피주문자
      parameters:
      - description: 판매자 ID
        in: query
        name: SellerID
        type: string
      - description: 메뉴이름
        in: query
        name: MenuName
        type: string
      - description: 가격
        in: query
        name: Price
        type: integer
      - description: 원산지
        enum:
        - 한국
        - 일본
        - 중국
        in: query
        name: CountryOf
        type: string
      - description: 메뉴 카테고리
        enum:
        - 한식
        - 일식
        - 중식
        in: query
        name: Category
        type: string
      - description: 주문 가능 상태
        enum:
        - 준비중
        - 판매중
        - 판매완료
        in: query
        name: Status
        type: string
      - description: 맵기
        enum:
        - 아주매움
        - 매움
        - 보통
        - 순한맛
        in: query
        name: Spicy
        type: string
      - description: 오늘의 추천메뉴 여부
        in: query
        name: TodayMenu
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call SearchMenu, return ok by json.
  /oos/order/searchOrder:
    get:
      consumes:
      - application/json
      description: SearchOrder 주문 내역 조회 기능 - 주문자
      parameters:
      - description: 주문자 ID
        in: query
        name: OrdererID
        required: true
        type: string
      - description: 메뉴이름
        in: query
        name: MenuName
        type: string
      - description: 주문 상태
        enum:
        - 주문확인중
        - 조리중
        - 배달중
        - 배달완료
        - 주문취소
        in: query
        name: OrderStatus
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call SearchOrder, return ok by json.
  /oos/order/searchTodayMenu:
    get:
      consumes:
      - application/json
      description: SearchTodayMenu 오늘의 추천메뉴 리스트
      parameters:
      - description: 판매자 ID
        in: query
        name: SellerID
        type: string
      - description: 메뉴이름
        in: query
        name: MenuName
        type: string
      - description: 가격
        in: query
        name: Price
        type: integer
      - description: 원산지
        enum:
        - 한국
        - 일본
        - 중국
        in: query
        name: CountryOf
        type: string
      - description: 메뉴 카테고리
        enum:
        - 한식
        - 일식
        - 중식
        in: query
        name: Category
        type: string
      - description: 주문 가능 상태
        enum:
        - 준비중
        - 판매중
        in: query
        name: Status
        type: string
      - description: 맵기
        enum:
        - 아주매움
        - 매움
        - 보통
        - 순한맛
        in: query
        name: Spicy
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call SearchTodayMenu, return ok by json.
  /oos/order/viewMenu:
    get:
      consumes:
      - application/json
      description: ViewMenu 메뉴 상세 - 주문자, 피주문자
      parameters:
      - description: 메뉴 ID
        in: query
        name: MenuID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: call ViewMenu, return ok by json.
  /oos/order/viewOrder:
    get:
      consumes:
      - application/json
      description: ViewOrder 주문 상세 - 주문자, 피주문자
      parameters:
      - description: 주문번호
        in: query
        name: OrderNo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call ViewOrder, return ok by json.
  /oos/seller/createMenu:
    post:
      consumes:
      - application/json
      description: CreateMenu 메뉴 등록 - 피주문자
      parameters:
      - description: 메뉴
        in: body
        name: Menu
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: call CreateMenu, return ok by json.
  /oos/seller/deleteMenu:
    put:
      consumes:
      - application/json
      description: DeleteMenu 메뉴 삭제 - 피주문자 (판매여부 bool 설정변경)
      parameters:
      - description: 메뉴
        in: body
        name: Menu
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: call DeleteMenu, return ok by json.
  /oos/seller/orderStatus:
    get:
      consumes:
      - application/json
      description: OrderStatus 주문 내역 조회 - 피주문자 (판매자ID 기준으로 검색)
      parameters:
      - description: 판매자 ID
        in: query
        name: SellerID
        required: true
        type: string
      - description: 주문 상태
        enum:
        - 주문확인중
        - 조리중
        - 배달중
        - 배달완료
        - 주문취소
        in: query
        name: OrderStatus
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call OrderStatus, return ok by json.
  /oos/seller/setTodayMenu:
    put:
      consumes:
      - application/json
      description: SetTodayMenu 오늘의 추천메뉴 여부 - 설정 변경 (메뉴ID를 기준으로 메뉴 업데이트)
      parameters:
      - description: 메뉴
        in: body
        name: Menu
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: call SetTodayMenu, return ok by json.
  /oos/seller/updateMenu:
    post:
      consumes:
      - application/json
      description: UpdateMenu 메뉴 수정 - 피주문자 (메뉴ID를 기준으로 메뉴 업데이트)
      parameters:
      - description: 메뉴
        in: body
        name: Menu
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: call UpdateMenu, return ok by json.
swagger: "2.0"
