definitions:
  controller.Controller:
    type: object
  model.Menu:
    properties:
      category:
        description: "수정내용\n\t메뉴 카테고리를 별도의 구조체로 생성해서 메뉴에 카테고리를 0~2개 이상의 값을 지니도록 수정"
        items:
          type: string
        type: array
      countryOf:
        description: 원산지 Enums(한국, 일본, 중국)
        type: string
      isRecommeded:
        description: "bool 값들의 경우는 네이밍시에 일반적으로 긍정의 단어를 사용하고, 그 여부는 true, false로 제어합니다.\n\t\t즉,
          추천드리는 네이밍은 IsAvailable, IsPublic, ForSale 이 되겠습니다.\n\t\tdisable이라는 부정의 의미보다는
          긍정의 의미로 네이밍을 짓고 변수 값으로 여부를 판단하는 것이 더 읽기에 자연스럽습니다.\n\n\t\t수정내용\n\t\t명칭 변경\n\t\tIsDisabled
          > IsRecommeded\n\t\tTodayMenu > IsTdoayMenu"
        type: boolean
      isTdoayMenu:
        description: "TodayMenu만 보고서는 bool 값인지 유추하기가 힘들어 보입니다. 현재는 오늘의 메뉴가 무엇인지 하는
          String 데이터가 예상이 됩니다.\n\t\t따라서 IsRecommeded, IsTdoayMenu 과 같은 네이밍이 적절해 보입니다."
        type: boolean
      maxCount:
        description: 판매 가능 갯수 mininum(1) maxinum(50)
        maximum: 50
        minimum: 1
        type: integer
      menuID:
        description: 메뉴 ID
        type: string
      menuName:
        description: 메뉴 이름
        type: string
      popularity:
        description: 인기도 mininum(1) maxinum(5)
        maximum: 5
        minimum: 1
        type: integer
      price:
        description: 가격
        type: integer
      sellerID:
        description: 판매자 ID
        type: string
      sellerName:
        description: 판매자 이름
        type: string
      spicy:
        description: 맵기 Enums(아주매움, 매움, 보통, 순한맛)
        type: string
      status:
        description: 주문 가능 상태 nums(준비중, 판매중)
        type: string
    type: object
  model.OrdererMenuLink:
    properties:
      menuID:
        description: 메뉴 ID
        type: string
      menuName:
        description: 메뉴이름
        type: string
      orderComment:
        description: 후기
        type: string
      orderNo:
        description: 주문번호
        type: string
      orderStarGrade:
        description: 평점 mininum(1) maxinum(5)
        maximum: 5
        minimum: 1
        type: integer
      orderStatus:
        description: 주문상태 Enums(주문확인중 - 조리중 - 배달중 - 배달완료 - 주문취소)
        type: string
      ordererAddress:
        description: 주문자 주소
        type: string
      ordererID:
        description: 주문자ID
        type: string
      ordererPhone:
        description: 주문자 폰번호
        type: integer
      sellerID:
        description: 판매자 ID
        type: string
    type: object
info:
  contact: {}
  description: 띵동주문이요, 온라인 주문 시스템(Online Ordering System)
  title: WBA [Backend Final Project]
  version: "1.0"
paths:
  /oos/order/changeOrder:
    put:
      consumes:
      - application/json
      description: ChangeOrder 주문 변경 - 주문자 (주문변경 커멘드 Enums(주문추가, 주문취소, 정보변경))
      parameters:
      - description: 오더
        in: body
        name: OrdererMenuLink
        required: true
        schema:
          $ref: '#/definitions/model.OrdererMenuLink'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call ChangeOrder, return ok by json.
  /oos/order/createReview:
    post:
      consumes:
      - application/json
      description: CreateReview 리뷰 등록 - 주문자 (주문번호 기준으로 등록)
      parameters:
      - description: 오더
        in: body
        name: OrdererMenuLink
        required: true
        schema:
          $ref: '#/definitions/model.OrdererMenuLink'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OrdererMenuLink'
      summary: call CreateReview, return ok by json.
  /oos/order/newOrder:
    post:
      consumes:
      - application/json
      description: NewOrder 주문 등록 - 주문자
      parameters:
      - description: 오더
        in: body
        name: OrdererMenuLink
        required: true
        schema:
          $ref: '#/definitions/model.OrdererMenuLink'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OrdererMenuLink'
      summary: call NewOrder, return ok by json.
  /oos/order/searchOrder:
    get:
      consumes:
      - application/json
      description: SearchOrder 주문 내역 조회 기능 - 주문자
      parameters:
      - description: 주문자 ID
        in: query
        name: OrdererID
        required: true
        type: string
      - description: 메뉴이름
        in: query
        name: MenuName
        type: string
      - description: 주문 상태
        enum:
        - 주문확인중
        - 조리중
        - 배달중
        - 배달완료
        - 주문취소
        in: query
        name: OrderStatus
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call SearchOrder, return ok by json.
  /oos/order/searchTodayMenu:
    get:
      consumes:
      - application/json
      description: SearchTodayMenu 오늘의 추천메뉴 리스트
      parameters:
      - description: 판매자 ID
        in: query
        name: SellerID
        type: string
      - description: 메뉴이름
        in: query
        name: MenuName
        type: string
      - description: 가격
        in: query
        name: Price
        type: integer
      - description: 원산지
        enum:
        - 한국
        - 일본
        - 중국
        in: query
        name: CountryOf
        type: string
      - description: 메뉴 카테고리
        enum:
        - 한식
        - 일식
        - 중식
        in: query
        name: Category
        type: string
      - description: 주문 가능 상태
        enum:
        - 준비중
        - 판매중
        in: query
        name: Status
        type: string
      - description: 맵기
        enum:
        - 아주매움
        - 매움
        - 보통
        - 순한맛
        in: query
        name: Spicy
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call SearchTodayMenu, return ok by json.
  /oos/order/viewMenu:
    get:
      consumes:
      - application/json
      description: ViewMenu 메뉴 상세 - 주문자, 피주문자
      parameters:
      - description: 메뉴 ID
        in: query
        name: MenuID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: call ViewMenu, return ok by json.
  /oos/order/viewOrder:
    get:
      consumes:
      - application/json
      description: ViewOrder 주문 상세 - 주문자, 피주문자
      parameters:
      - description: 주문번호
        in: query
        name: OrderNo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call ViewOrder, return ok by json.
  /oos/seller/menu:
    delete:
      consumes:
      - application/json
      description: DeleteMenu 메뉴 삭제 - 피주문자 (판매여부 bool 설정변경)
      parameters:
      - description: menuID
        in: query
        name: menuID
        required: true
        type: string
      - description: isRecommeded
        in: query
        name: isRecommeded
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: call DeleteMenu, return ok by json.
    get:
      consumes:
      - application/json
      description: SearchMenu 메뉴 검색 - 주문자, 피주문자
      parameters:
      - description: 판매자 ID
        in: query
        name: SellerID
        type: string
      - description: 메뉴이름
        in: query
        name: MenuName
        type: string
      - description: 가격
        in: query
        name: Price
        type: integer
      - description: 원산지
        enum:
        - 한국
        - 일본
        - 중국
        in: query
        name: CountryOf
        type: string
      - description: 메뉴 카테고리
        enum:
        - 한식
        - 일식
        - 중식
        in: query
        name: Category
        type: string
      - description: 주문 가능 상태
        enum:
        - 준비중
        - 판매중
        - 판매완료
        in: query
        name: Status
        type: string
      - description: 맵기
        enum:
        - 아주매움
        - 매움
        - 보통
        - 순한맛
        in: query
        name: Spicy
        type: string
      - description: 오늘의 추천메뉴 여부
        in: query
        name: TodayMenu
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call SearchMenu, return ok by json.
    post:
      consumes:
      - application/json
      description: CreateMenu 메뉴 등록 - 피주문자
      parameters:
      - description: 메뉴
        in: body
        name: Menu
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: call CreateMenu, return ok by json.
  /oos/seller/menu/{menuID}:
    put:
      consumes:
      - application/json
      description: UpdateMenu 메뉴 수정 - 피주문자 (메뉴ID를 기준으로 메뉴 업데이트)
      parameters:
      - description: menuID
        in: path
        name: menuID
        required: true
        type: string
      - description: 변경할 메뉴
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: call UpdateMenu, return ok by json.
  /oos/seller/orderStatus:
    get:
      consumes:
      - application/json
      description: OrderStatus 주문 내역 조회 - 피주문자 (판매자ID 기준으로 검색)
      parameters:
      - description: 판매자 ID
        in: query
        name: SellerID
        required: true
        type: string
      - description: 주문 상태
        enum:
        - 주문확인중
        - 조리중
        - 배달중
        - 배달완료
        - 주문취소
        in: query
        name: OrderStatus
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call OrderStatus, return ok by json.
  /oos/seller/setTodayMenu:
    put:
      consumes:
      - application/json
      description: SetTodayMenu 오늘의 추천메뉴 여부 - 설정 변경 (메뉴ID를 기준으로 메뉴 업데이트)
      parameters:
      - description: 메뉴
        in: body
        name: Menu
        required: true
        schema:
          $ref: '#/definitions/model.Menu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Menu'
      summary: call SetTodayMenu, return ok by json.
swagger: "2.0"
